name: Frontend CI

on:
  push:
    branches:
      - main
      - develop
      - david
  pull_request:
    branches:
      - main
      - develop

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: |
          cd frontend-scientists
          npm install

      - name: Correr tests
        run: |
          cd frontend
          npm run test

